name: Neuron Library Build Jobs.
on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      ubuntu_distro:
        description: "Neuron Library Target Ubuntu Version. Could be `1804` or `2004`"
        required: true
        default: "2004"

jobs:
  build-neuron-library:
    runs-on: [self-hosted, Linux, X64, matrix-dev]
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - uses: uraimo/run-on-arch-action@v2.0.5
        name: Run on aarch64
        with:
          arch: aarch64
          distro: ubuntu18.04
          install: |
            apt update -q -y
            apt install -q -y git build-essential swig3.0 python-dev python3 python3-dev nodejs-dev cmake libjson-c-dev curl pkg-config
          run: |
            echo ${{env.RELEASE_VERSION}}
            cmake -B/tmp/build -H. -DBUILDSWIGNODE=OFF
            cmake --build /tmp/build --target package
            if [ -f "/tmp/build/neuron-library_${{env.RELEASE_VERSION}}_arm64.deb" ]; then
              echo "\nRemove existing neuron-library debian package\n"
              curl -X DELETE http://website:10080/api/files/neuron-library
              echo "\nAdding package neuron-library debian package to local storage\n"
              curl -X POST -F file=@/tmp/build/neuron-library_${{env.RELEASE_VERSION}}_arm64.deb http://website:10080/api/files/neuron-library
              sleep 0.5
              echo "Posting folder neuron-library to repo bionic-common"
              curl -X POST http://website:10080/api/repos/bionic-common/file/neuron-library?noRemove=1
              sleep 0.5
              echo "Posting folder neuron-library to repo focal-common"
              curl -X POST http://website:10080/api/repos/focal-common/file/neuron-library?noRemove=1
              echo "\nRemove existing neuron-library deb files\n"
              curl -X DELETE http://website:10080/api/files/neuron-library
            fi